# Generated by Mistral 7B via Ollama

class Solution:
    def findLength(self, nums1, nums2):
        for i in range(min(len(nums1), len(nums2))):
            if nums1[i] == nums2[i]:
                common_subarray = [nums1[j] for j in range(i)] + [nums2[j] for j in range(i)]
                if self.findLength(common_subarray, nums1[i+1:]) and self.findLength(nums2[i+1:], common_subarray):
                    return len(common_subarray) + self.findLength(nums1[i+1:], nums2[i+1:])
        return 0

