# Generated by Mistral 7B via Ollama
from typing import List

class Solution:
    def maxResult(self, nums: List[int], k: int) -> int:
        n = len(nums)
        dp = [[float('-inf') for _ in range(k+1)] for _ in range(n)]
        dp[-1][0] = nums[-1] if n > 1 else 0
        for i in range(n - 2, -1, -1):
            for j in range(min(k, i + 1), -1, -1):
                dp[i][j] = max(dp[i][j], dp[i+1][j+1] + nums[i]) if i + 1 < n else nums[i]
        return max(dp[0])

