# Generated by Mistral 7B via Ollama

class Solution:
    def minimumVisitedCells(self, grid):
        m, n = len(grid), len(grid[0])
        visited = set()
        queue = [(0, 0)]

        while queue:
            i, j = queue.pop(0)
            if (i, j) == (m - 1, n - 1):
                return len(visited)

            for di, dj in ((0, 1), (1, 0)):
                k = i + di * grid[i][j]
                if not (k < m and grid[k][j] == 0):
                    continue
                queue.append((k, j))
                visited.add((i, j))

        return -1

