# Generated by Mistral 7B via Ollama

class Solution:
    def fib(self, n):
        if n <= 0 or n > 30:
            raise ValueError("Input should be between 0 and 30")
        if n == 0:
            return 0
        elif n == 1:
            return 1
        else:
            fib_sequence = [0, 1]
            for i in range(2, n + 1):
                fib_sequence.append(fib_sequence[-1] + fib_sequence[-2])
            return fib_sequence[n]

