# Generated by Mistral 7B via Ollama

class Solution:
    def coinChange(self, coins, amount):
        if not coins or amount < 1:
            return -1
        dp = [float('inf')] * (amount + 1)
        dp[0] = 0
        for i in range(len(coins)):
            for j in range(coins[i], amount + 1):
                dp[j] = min(dp[j], dp[j - coins[i]] + 1)
        return dp[-1]

