# Generated by Mistral 7B via Ollama

class Solution:
    def getMaximumGenerated(self, n: int) -> int:
        if n == 0 or n == 1:
            return n
        odd = [1]
        even = [0]
        i = 2
        while i <= n:
            oddeven = odd[i//2] if i%2 else even[i//2]+odd[(i+1)//2]
            odd.append(oddeven)
            even.append(oddeven)
            i += 1
        return max(odd[:n+1])

