# Generated by Mistral 7B via Ollama

class Solution:
    def maxEnvelopes(self, envelopes):
        if not envelopes: return 0
        envelopes.sort(key=lambda x: (x[0], -x[1]))
        stack = []
        for envelope in envelopes:
            while stack and stack[-1][0] > envelope[0]:
                stack.pop()
            if not stack or stack[-1][1] > envelope[1]:
                stack.append(envelope)
        return len(stack)

