# Generated by Mistral 7B via Ollama

class Solution:
    def uniqueLetterString(self, s):
        return len(s) - sum([s.count(c) > 1 for c in s])

    def uniqueLetterString(self, s: str) -> int:
        power = 0
        dp = [0] * (len(s) + 1)
        for i in range(len(s)):
            power += self.countUniqueChars(s[i])
            dp[i+1] = dp[i] + power
        return sum(dp)

