# Generated by Mistral 7B via Ollama

class Solution:
    def getRow(self, rowIndex):
        memo = [1]
        for _ in range(1, rowIndex + 1):
            row = [memo[i] * (rowIndex - i) // i for i in range(rowIndex + 1)]
            row.insert(0, 1)
            memo = row
        return memo

