# Generated by Mistral 7B via Ollama

class Solution:
    def isSubsequence(self, s, t):
        if not s:
            return True

        i = j = 0
        while j < len(t) and i < len(s):
            if t[j] == s[i]:
                i += 1
            j += 1
        return i == len(s)

    def isSubsequence(self, strings, t):
        subsequences = [x for x in strings if self.isSubsequence(x, t)]
        return len(subsequences) > 0

