# Generated by Mistral 7B via Ollama

class Solution:
    def subarrayBitwiseORs(self, arr):
        n = len(arr)
        bitmasks = [set() for _ in range(n + 1)]
        result = set()
        for i, num in enumerate(arr):
            for j in range(i + 1, n + 1):
                bitmasks[j].add(num | bitmasks[i][0])
            for mask in bitmasks[i + 1]:
                result.add(mask)
        return len(result)

